import dict_emojis, dict_actions

monsters_attributes = {
    # RATS ACT I FIRST PART
    "Phat Rat": {
        'id': 0,
        'character_class': 'Phat Rat',
        'name': 'Phat Rat',
        'level': 1,
        'experience': 0,
        'vitality': 40,
        'power': 6,
        'defense': 10,
        'critical': 1,
        'speed': 1,
        'taunt': 4,
        'accuracy': 70,
        'dodge': 0,
        'skill1': None,
        'skill2': None,
        'emoji': dict_emojis.monsters["Phat Rat"],
        'attack': dict_actions.monsters_attack["Phat Rat"]
    },
    "Even Phatter Rat": {
        'id': 0,
        'character_class': 'Even Phatter Rat',
        'name': 'Even Phatter Rat',
        'level': 2,
        'experience': 0,
        'vitality': 80,
        'power': 10,
        'defense': 20,
        'critical': 1,
        'speed': 1,
        'taunt': 8,
        'accuracy': 70,
        'dodge': 0,
        'skill1': None,
        'skill2': None,
        'emoji': dict_emojis.monsters["Even Phatter Rat"],
        'attack': dict_actions.monsters_attack["Even Phatter Rat"]
    },
    "Sewer Skewer": {
        'id': 0,
        'character_class': 'Sewer Skewer',
        'name': 'Sewer Skewer',
        'level': 2,
        'experience': 0,
        'vitality': 60,
        'power': 22,
        'defense': 12,
        'critical': 5,
        'speed': 5,
        'taunt': 1,
        'accuracy': 75,
        'dodge': 0,
        'skill1': dict_actions.skills1["Skewer Thrust"],
        'skill2': None,
        'emoji': dict_emojis.monsters["Sewer Skewer"],
        'attack': dict_actions.monsters_attack["Sewer Skewer"]
    },
    "Protein Gnawer": {
        'id': 0,
        'character_class': 'Protein Gnawer',
        'name': 'Protein Gnawer',
        'level': 3,
        'experience': 0,
        'vitality': 140,
        'power': 50,
        'defense': 20,
        'critical': 10,
        'speed': 1,
        'taunt': 4,
        'accuracy': 70,
        'dodge': 0,
        'skill1': dict_actions.skills1["Abs Avalanche"],
        'skill2': None,
        'emoji': dict_emojis.monsters["Protein Gnawer"],
        'attack': dict_actions.monsters_attack["Protein Gnawer"]
    },
    "Ratgabash the Wicked": {
        'id': 0,
        'character_class': 'Ratgabash the Wicked',
        'name': 'Ratgabash the Wicked',
        'level': 4,
        'experience': 0,
        'vitality': 100,
        'power': 50,
        'defense': 20,
        'critical': 10,
        'speed': 5,
        'taunt': 2,
        'accuracy': 90,
        'dodge': 5,
        'skill1': dict_actions.skills1["Poison Cloud"],
        'skill2': dict_actions.skills2["Rat Swarm"],
        'emoji': dict_emojis.monsters["Ratgabash the Wicked"],
        'attack': dict_actions.monsters_attack["Ratgabash the Wicked"]
    },
    # PIGS ACT I SECOND PART
    "Bricklayer Piglet": {
        'id': 0,
        'character_class': 'Bricklayer Piglet',
        'name': 'Bricklayer Piglet',
        'level': 4,
        'experience': 0,
        'vitality': 140,
        'power': 60,
        'defense': 30,
        'critical': 5,
        'speed': 3,
        'taunt': 5,
        'accuracy': 90,
        'dodge': 5,
        'skill1': dict_actions.skills1["Bacon Slap"],
        'skill2': None,
        'emoji': dict_emojis.monsters["Three Pigs"],
        'attack': dict_actions.monsters_attack["Three Pigs"]
    },  
    "Carpenter Piglet": {
        'id': 0,
        'character_class': 'Carpenter Piglet',
        'name': 'Carpenter Piglet',
        'level': 4,
        'experience': 0,
        'vitality': 140,
        'power': 60,
        'defense': 30,
        'critical': 5,
        'speed': 3,
        'taunt': 5,
        'accuracy': 90,
        'dodge': 5,
        'skill1': dict_actions.skills1["Bacon Slap"],
        'skill2': None,
        'emoji': dict_emojis.monsters["Three Pigs"],
        'attack': dict_actions.monsters_attack["Three Pigs"]
    },      
    "Farmer Piglet": {
        'id': 0,
        'character_class': 'Farmer Piglet',
        'name': 'Farmer Piglet',
        'level': 4,
        'experience': 0,
        'vitality': 140,
        'power': 60,
        'defense': 30,
        'critical': 5,
        'speed': 3,
        'taunt': 5,
        'accuracy': 90,
        'dodge': 5,
        'skill1': dict_actions.skills1["Bacon Slap"],
        'skill2': None,
        'emoji': dict_emojis.monsters["Three Pigs"],
        'attack': dict_actions.monsters_attack["Three Pigs"]
    },
    "Sumo Pig": {
        'id': 0,
        'character_class': 'Sumo Pig',
        'name': 'Sumo Pig',
        'level': 13,
        'experience': 0,
        'vitality': 400,
        'power': 100,
        'defense': 80,
        'critical': 20,
        'speed': 1,
        'taunt': 100,
        'accuracy': 90,
        'dodge': 0,
        'skill1': dict_actions.skills1["Bacon Slap"],
        'skill2': dict_actions.skills1["Massive Body Slam"],
        'emoji': dict_emojis.monsters["Sumo Pig"],
        'attack': dict_actions.monsters_attack["Sumo Pig"]
    },    
}


