skills1 = {
    None: None,
    "Abs Avalanche": {
        'attribute': 'power',
        'base_value': 25,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Abs Avalanche',
        'number_target': 2,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 20,
    },
    "Backstab": {
        'attribute': 'power',
        'base_value': 20,
        'critical_modifier': 10,
        'critical_multiplier': 3,
        'is_target_enemy': True,
        'name': 'Backstab',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 1000,
    },
    "Bacon Slap": {
        'attribute': 'power',
        'base_value': 22,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Bacon Slap',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 20,
    },
    "Berserk": {
        'attribute': 'power',
        'base_value': 15,
        'critical_modifier': 20,
        'critical_multiplier': 2.5,
        'is_target_enemy': True,
        'name': 'Berserk',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 0,
        "special": "chain"
    },
    "Cleave": {
        'attribute': 'power',
        'base_value': 25,
        'critical_modifier': 10,
        'critical_multiplier': 1.5,
        'is_target_enemy': True,
        'name': 'Cleave',
        'number_target': 2,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': -10,
    },
    "Fireball": {
        'attribute': 'magic',
        'base_value': 12,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Fireball',
        'number_target': 3,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 0,        
        'apply_conditions': {
            'burn': {
                "value": [10,1],
                "apply_to": 'target'
            }
        }
    },
    "Greasy Heal": {
        'attribute': 'heal',
        'base_value': 25,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': False,
        'name': 'Greasy Heal',
        'number_target': 1,
        'text': 'heals',
        'type': 'heal',
        'accuracy_modifier': 0,
        'apply_conditions': {
            'protection': {
                "value": True,
                "apply_to": 'target'
            }
        }
    },
    "Headshot": {
        'attribute': 'power',
        'base_value': 15,
        'critical_modifier': 1000,
        'critical_multiplier': 4,
        'is_target_enemy': True,
        'name': 'Headshot',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': -50,
    },
    "Lightning Bolt": {
        'attribute': 'magic',
        'base_value': 35,
        'critical_modifier': -1000,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Lightning Bolt',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 0,
        'apply_conditions': {
            'shock': {
                "value": True,
                "apply_to": 'target'
            }
        }
    },
    "Massive Body Slam": {
        'attribute': 'power',
        'base_value': 25,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Massive Body Slam',
        'number_target': 3,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 1000, 
    },
    "Poison Cloud": {
        'attribute': 'power',
        'base_value': 20,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Poison Cloud',
        'number_target': 2,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 1000,
        'apply_conditions': {
            'poison': {
                "value": 6,
                "apply_to": 'target'
            }

        }
    },
    "Shadowstep": {
        'attribute': 'power',
        'base_value': 10,
        'critical_modifier': 20,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Shadowstep',
        'number_target': 3,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 0,
    },
    "Skewer Thrust": {
        'attribute': 'power',
        'base_value': 22,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Skewer Thrust',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 20,
        'apply_conditions': {
            'bleed': {
                "value": [7,2],
                "apply_to": 'target'
            }
        }
    },
    "Swing": {
        'attribute': 'power',
        'base_value': 15,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Swing',
        'number_target': 3,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': -20,
    },
    "Volley": {
        'attribute': 'power',
        'base_value': 12,
        'critical_modifier': 25,
        'critical_multiplier': 2.5,
        'is_target_enemy': True,
        'name': 'Volley',
        'number_target': 2,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': -25,
    },
}

skills2 = {
    None: None,
    "Burning Ground": {
    'attribute': 'magic',
    'base_value': 1,
    'critical_modifier': -1000,
    'critical_multiplier': 2,
    'is_target_enemy': True,
    'name': 'Burning Ground',
    'number_target': 3,
    'text': 'attacks',
    'type': 'attack',
    'accuracy_modifier': 1000,        
    'apply_conditions': {
        'burn': {
            "value": [30,3],
            "apply_to": 'target'
            }
        }
    },
    "Cutthroat": {
        'attribute': None,
        'base_value': 50,
        'critical_modifier': -1000,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Cutthroat',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': -50,
    },
    "Finger of Death": {
        'attribute': None,
        'base_value': 60,
        'critical_modifier': -1000,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Finger of Death',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': -50,
    },
    "Heroic Strike": {
        'attribute': 'power',
        'base_value': 40,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Heroic Strike',
        'number_target': 1,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 1000,
    },
    "Rain of Arrows": {
        'attribute': None,
        'base_value': 22,
        'critical_modifier': 0,
        'critical_multiplier': 3,
        'is_target_enemy': True,
        'name': 'Rain of Arrows',
        'number_target': 3,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 100,
    },
    "Rat Swarm": {
        'attribute': 'magic',
        'base_value': 30,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': True,
        'name': 'Rat Swarm',
        'number_target': 3,
        'text': 'attacks',
        'type': 'attack',
        'accuracy_modifier': 1000,
    },
    "Sanctuary": {
        'attribute': 'magic',
        'base_value': 20,
        'critical_modifier': 0,
        'critical_multiplier': 2,
        'is_target_enemy': False,
        'name': 'Sanctuary',
        'number_target': 3,
        'text': 'heals',
        'type': 'heal',
        'accuracy_modifier': 0,
    },
}

characters_attack = {
    "Grizzor": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 15,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Whizz": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 12,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Slink": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 12,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 3,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Quill": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 18,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Pigwell": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 12,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
}

monsters_attack = {
    "Phat Rat": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 8,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Even Phatter Rat": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 12,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Sewer Skewer": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 12,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Squeallo, the Over Roasted": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 6,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
        'apply_conditions': {
            'burn': {
                "value": [10,1],
                "apply_to": 'target'
            },
        },
    },
    "Hamlet Swinesword": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 22,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Protein Gnawer": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 18,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Ratgabash the Wicked": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 12,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Three Pigs": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 16,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
    "Sumo Pig": {
        'type': 'attack',
        'attribute': 'power',
        'text': 'attacks',
        'name': 'Basic Attack',
        'base_value': 20,
        'is_target_enemy': True,
        'number_target': 1,
        'critical_multiplier': 2,
        'critical_modifier': 0,
        'accuracy_modifier': 0,
    },
}

 